#!/bin/sh
# ============================================================================
# Script: update-changelog.sh
# Description: Commit and push changelog to feature/hotfix branch
# Inputs: /tmp/scenario.env, VERSIONING_BRANCH, VERSIONING_PR_ID (env)
# Outputs: Committed and pushed CHANGELOG.md
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/../lib/common.sh"
. "${SCRIPT_DIR}/../lib/config-parser.sh"

# Load configuration
CHANGELOG_FILE=$(get_changelog_file)
CHANGELOG_TITLE=$(get_changelog_title)

# Check if CHANGELOG has changes (modified or new file)
changelog_has_changes() {
    # Check if file is modified
    if ! git diff --quiet "$CHANGELOG_FILE" 2>/dev/null; then
        return 0
    fi
    # Check if file is new (untracked)
    if [ -f "$CHANGELOG_FILE" ] && ! git ls-files --error-unmatch "$CHANGELOG_FILE" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

# Get list of version files that were modified
get_version_files_modified() {
    read_state "/tmp/version_files_modified.txt" || true
}

# Check if any version files were modified
has_version_files_modified() {
    local files=$(get_version_files_modified)
    [ -n "$files" ]
}

# Load scenario
load_env "/tmp/scenario.env"

# Handle development and hotfix releases through the same unified flow.
# The (Hotfix) header marker is injected upstream by the CHANGELOG generators,
# so the commit staging / messaging / push logic here is scenario-agnostic.
if [ "$SCENARIO" = "development_release" ] || [ "$SCENARIO" = "hotfix" ]; then
    if [ ! -f "/tmp/next_version.txt" ]; then
        exit 0
    fi

    # Check if we have any changes to commit (CHANGELOG, version files, or per-folder changelogs)
    HAS_CHANGELOG_CHANGES=false
    HAS_VERSION_FILES=false
    HAS_PER_FOLDER_CHANGELOGS=false

    if changelog_has_changes; then
        HAS_CHANGELOG_CHANGES=true
    fi

    if has_version_files_modified; then
        HAS_VERSION_FILES=true
    fi

    if [ -f "/tmp/per_folder_changelogs.txt" ] && [ -s "/tmp/per_folder_changelogs.txt" ]; then
        HAS_PER_FOLDER_CHANGELOGS=true
    fi

    if [ "$HAS_CHANGELOG_CHANGES" = "true" ] || [ "$HAS_VERSION_FILES" = "true" ] || [ "$HAS_PER_FOLDER_CHANGELOGS" = "true" ]; then
        log_info "Changes detected - proceeding to commit"

        NEXT_VERSION=$(read_state "/tmp/next_version.txt")
        BUMP_TYPE=$(read_state "/tmp/bump_type.txt")

        log_section "COMMITTING CHANGES TO FEATURE BRANCH"

        # Stage CHANGELOG
        if [ "$HAS_CHANGELOG_CHANGES" = "true" ]; then
            log_info "Staging: $CHANGELOG_FILE"
            git add "$CHANGELOG_FILE"
        fi

        # Stage version files
        if [ "$HAS_VERSION_FILES" = "true" ]; then
            VERSION_FILES=$(get_version_files_modified)
            for file in $VERSION_FILES; do
                if [ -n "$file" ] && [ -f "$file" ]; then
                    log_info "Staging: $file"
                    git add "$file"
                fi
            done
        fi

        # Stage per-folder changelogs
        if [ "$HAS_PER_FOLDER_CHANGELOGS" = "true" ]; then
            sort -u /tmp/per_folder_changelogs.txt | while IFS= read -r cl; do
                if [ -n "$cl" ] && [ -f "$cl" ]; then
                    log_info "Staging: $cl"
                    git add "$cl"
                fi
            done
        fi

        if [ -n "${VERSIONING_PR_ID:-}" ]; then
            # PR context: commit with [skip ci], push to feature branch
            git commit -m "chore(release): update CHANGELOG for version $NEXT_VERSION ($BUMP_TYPE bump) [skip ci]" \
                -m "" \
                -m "This CHANGELOG will be included in the merge to ${VERSIONING_TARGET_BRANCH}." \
                -m "After merge, the version tag will be created automatically." \
                -m "" \
                -m "Generated by CI Pipeline" \
                -m "Branch: $VERSIONING_BRANCH" \
                -m "PR: #$VERSIONING_PR_ID"

            log_success "Changes committed successfully"
            echo ""

            log_info "Pushing commit to feature branch..."
            git_push_branch "$VERSIONING_BRANCH"

            log_section "PR CHANGELOG GENERATION COMPLETE"
        else
            # Branch context: commit only — push is handled by branch-pipeline.sh (atomic with tag)
            git commit -m "chore(release): update CHANGELOG for version $NEXT_VERSION ($BUMP_TYPE bump) [skip ci]" \
                -m "" \
                -m "Generated by CI Pipeline" \
                -m "Branch: $VERSIONING_BRANCH"

            log_success "Changes committed successfully"
            echo ""

            # Signal to branch-pipeline.sh that a CHANGELOG commit exists and needs pushing
            touch /tmp/changelog_committed.flag
            log_info "CHANGELOG committed — push deferred to branch-pipeline.sh (atomic with tag)"

            log_section "BRANCH CHANGELOG GENERATION COMPLETE"
        fi

        log_info "Next Version: $NEXT_VERSION"
        log_info "Bump Type:    $BUMP_TYPE"
        echo ""
        log_info "$CHANGELOG_FILE has been updated"
        if [ "$HAS_VERSION_FILES" = "true" ]; then
            log_info "Version files have been updated"
        fi
        if [ "$HAS_PER_FOLDER_CHANGELOGS" = "true" ]; then
            log_info "Per-folder CHANGELOGs have been updated"
        fi
    else
        log_info "No changes to commit - already up to date"
        log_info "Pipeline complete (no commit needed)"
    fi
fi
