package changelog

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/PanoraGrowth/panora-versioning-pipe/internal/config"
	"github.com/PanoraGrowth/panora-versioning-pipe/internal/util/log"
)

// CommitAndPush stages and commits all changelog-related changes.
//
// Reads from the filesystem:
//   - CHANGELOG.md (checked for modifications)
//   - /tmp/version_files_modified.txt (optional list of version files)
//   - /tmp/per_folder_changelogs.txt  (optional list of per-folder changelogs)
//
// Branch context (prID == ""): commits only, writes /tmp/changelog_committed.flag.
// PR context (prID != ""):     commits + pushes to branch.
func CommitAndPush(cfg *config.Config, repoRoot, nextVersion, bumpType, branch, prID, targetBranch string) error {
	const op = "changelog.update"

	changelogFile := cfg.Changelog.File
	if changelogFile == "" {
		changelogFile = "CHANGELOG.md"
	}

	hasChangelog := changelogHasChanges(repoRoot, changelogFile)
	hasVersionFiles := hasVersionFilesModified()
	hasPerFolder := hasPerFolderChangelogs()

	if !hasChangelog && !hasVersionFiles && !hasPerFolder {
		log.Info("No changes to commit - already up to date")
		log.Info("Pipeline complete (no commit needed)")
		return nil
	}

	log.Info("Changes detected - proceeding to commit")
	log.Section("COMMITTING CHANGES TO FEATURE BRANCH")

	if hasChangelog {
		log.Info(fmt.Sprintf("Staging: %s", changelogFile))
		if err := gitAdd(repoRoot, changelogFile); err != nil {
			return fmt.Errorf("%s: stage changelog: %w", op, err)
		}
	}

	if hasVersionFiles {
		files := readLines("/tmp/version_files_modified.txt")
		for _, f := range files {
			if f == "" {
				continue
			}
			log.Info(fmt.Sprintf("Staging: %s", f))
			if err := gitAdd(repoRoot, f); err != nil {
				return fmt.Errorf("%s: stage version file %s: %w", op, f, err)
			}
		}
	}

	if hasPerFolder {
		files := readLinesUnique("/tmp/per_folder_changelogs.txt")
		for _, f := range files {
			if f == "" {
				continue
			}
			log.Info(fmt.Sprintf("Staging: %s", f))
			if err := gitAdd(repoRoot, f); err != nil {
				return fmt.Errorf("%s: stage per-folder changelog %s: %w", op, f, err)
			}
		}
	}

	// Build and run git commit
	var commitArgs []string
	if prID != "" {
		commitArgs = buildPRCommitArgs(nextVersion, bumpType, branch, prID, targetBranch)
	} else {
		commitArgs = buildBranchCommitArgs(nextVersion, bumpType, branch)
	}

	cmd := exec.Command("git", append([]string{"commit"}, commitArgs...)...)
	cmd.Dir = repoRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s: git commit: %w", op, err)
	}

	log.Success("Changes committed successfully")
	fmt.Println()

	if prID != "" {
		log.Info("Pushing commit to feature branch...")
		pushCmd := exec.Command("git", "push", "origin", branch)
		pushCmd.Dir = repoRoot
		pushCmd.Stdout = os.Stdout
		pushCmd.Stderr = os.Stderr
		if err := pushCmd.Run(); err != nil {
			return fmt.Errorf("%s: git push: %w", op, err)
		}
		log.Section("PR CHANGELOG GENERATION COMPLETE")
	} else {
		if err := os.WriteFile("/tmp/changelog_committed.flag", []byte{}, 0644); err != nil {
			return fmt.Errorf("%s: write flag: %w", op, err)
		}
		log.Info("CHANGELOG committed — push deferred to branch-pipeline.sh (atomic with tag)")
		log.Section("BRANCH CHANGELOG GENERATION COMPLETE")
	}

	log.Info(fmt.Sprintf("Next Version: %s", nextVersion))
	log.Info(fmt.Sprintf("Bump Type:    %s", bumpType))
	fmt.Println()
	log.Info(fmt.Sprintf("%s has been updated", changelogFile))
	if hasVersionFiles {
		log.Info("Version files have been updated")
	}
	if hasPerFolder {
		log.Info("Per-folder CHANGELOGs have been updated")
	}

	return nil
}

func buildPRCommitArgs(version, bumpType, branch, prID, targetBranch string) []string {
	return []string{
		"-m", fmt.Sprintf("chore(release): update CHANGELOG for version %s (%s bump) [skip ci]", version, bumpType),
		"-m", "",
		"-m", fmt.Sprintf("This CHANGELOG will be included in the merge to %s.", targetBranch),
		"-m", "After merge, the version tag will be created automatically.",
		"-m", "",
		"-m", "Generated by CI Pipeline",
		"-m", fmt.Sprintf("Branch: %s", branch),
		"-m", fmt.Sprintf("PR: #%s", prID),
	}
}

func buildBranchCommitArgs(version, bumpType, branch string) []string {
	return []string{
		"-m", fmt.Sprintf("chore(release): update CHANGELOG for version %s (%s bump) [skip ci]", version, bumpType),
		"-m", "",
		"-m", "Generated by CI Pipeline",
		"-m", fmt.Sprintf("Branch: %s", branch),
	}
}

// changelogHasChanges returns true if changelogFile has staged or unstaged changes,
// or exists as an untracked (new) file in the working tree.
func changelogHasChanges(repoRoot, changelogFile string) bool {
	// Staged changes (index vs HEAD): exit 1 = diff exists, exit 0 = no diff, other = error
	staged := exec.Command("git", "diff", "--cached", "--quiet", "--", changelogFile)
	staged.Dir = repoRoot
	if code := exitCode(staged.Run()); code == 1 {
		return true
	}
	// Unstaged changes (working tree vs index): exit 1 = diff, exit 0 = no diff
	unstaged := exec.Command("git", "diff", "--quiet", "--", changelogFile)
	unstaged.Dir = repoRoot
	if code := exitCode(unstaged.Run()); code == 1 {
		return true
	}
	// Untracked new file: not in index but exists on disk
	tracked := exec.Command("git", "ls-files", "--error-unmatch", "--", changelogFile)
	tracked.Dir = repoRoot
	if tracked.Run() != nil {
		// Not tracked — check if file exists on disk
		absPath := changelogFile
		if !strings.HasPrefix(absPath, "/") {
			absPath = repoRoot + "/" + changelogFile
		}
		if _, err := os.Stat(absPath); err == nil {
			return true
		}
	}
	return false
}

func exitCode(err error) int {
	if err == nil {
		return 0
	}
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		return exitErr.ExitCode()
	}
	return -1
}

func hasVersionFilesModified() bool {
	data, err := os.ReadFile("/tmp/version_files_modified.txt")
	return err == nil && strings.TrimSpace(string(data)) != ""
}

func hasPerFolderChangelogs() bool {
	data, err := os.ReadFile("/tmp/per_folder_changelogs.txt")
	return err == nil && strings.TrimSpace(string(data)) != ""
}

func readLines(path string) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	return strings.Split(strings.TrimSpace(string(data)), "\n")
}

func readLinesUnique(path string) []string {
	lines := readLines(path)
	seen := map[string]bool{}
	var result []string
	for _, l := range lines {
		if l != "" && !seen[l] {
			seen[l] = true
			result = append(result, l)
		}
	}
	return result
}

func gitAdd(repoRoot, path string) error {
	cmd := exec.Command("git", "add", path)
	cmd.Dir = repoRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
