package changelog

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/PanoraGrowth/panora-versioning-pipe/internal/util/log"
)

// UpdateOptions holds the inputs for CommitAndFlag.
type UpdateOptions struct {
	// ChangelogFile is the absolute path to the root CHANGELOG.md.
	ChangelogFile string
	// VersionFilesModifiedPath is the path to /tmp/version_files_modified.txt.
	VersionFilesModifiedPath string
	// PerFolderChangelogsPath is the path to /tmp/per_folder_changelogs.txt.
	PerFolderChangelogsPath string
	// NextVersion from /tmp/next_version.txt.
	NextVersion string
	// BumpType from /tmp/bump_type.txt.
	BumpType string
	// VersioningBranch (VERSIONING_BRANCH env).
	VersioningBranch string
	// VersioningTargetBranch (VERSIONING_TARGET_BRANCH env).
	VersioningTargetBranch string
	// PRContext: when VERSIONING_PR_ID is set, we commit + push to feature branch.
	// When empty, we commit only and write the flag file.
	PRID string
	// FlagPath is /tmp/changelog_committed.flag.
	FlagPath string
	// RepoPath is the absolute workspace path.
	RepoPath string
}

// CommitAndFlag implements update-changelog.sh.
//
// It stages CHANGELOG.md, version files, and per-folder changelogs, then
// commits and optionally pushes (PR context) or writes a flag file (branch
// context).
func CommitAndFlag(opts UpdateOptions) error {
	hasChangelog := changelogHasChanges(opts.ChangelogFile, opts.RepoPath)
	versionFiles := readVersionFiles(opts.VersionFilesModifiedPath)
	perFolderFiles := readPerFolderChangelogs(opts.PerFolderChangelogsPath)

	if !hasChangelog && len(versionFiles) == 0 && len(perFolderFiles) == 0 {
		log.Info("No changes to commit - already up to date")
		log.Info("Pipeline complete (no commit needed)")
		return nil
	}

	log.Info("Changes detected - proceeding to commit")
	log.Section("COMMITTING CHANGES TO FEATURE BRANCH")

	// Stage CHANGELOG
	if hasChangelog {
		log.Info(fmt.Sprintf("Staging: %s", opts.ChangelogFile))
		if err := gitAdd(opts.ChangelogFile, opts.RepoPath); err != nil {
			return err
		}
	}

	// Stage version files
	for _, f := range versionFiles {
		if f == "" {
			continue
		}
		if _, err := os.Stat(f); err == nil {
			log.Info(fmt.Sprintf("Staging: %s", f))
			if err := gitAdd(f, opts.RepoPath); err != nil {
				return err
			}
		}
	}

	// Stage per-folder changelogs
	for _, f := range perFolderFiles {
		if f == "" {
			continue
		}
		if _, err := os.Stat(f); err == nil {
			log.Info(fmt.Sprintf("Staging: %s", f))
			if err := gitAdd(f, opts.RepoPath); err != nil {
				return err
			}
		}
	}

	if opts.PRID != "" {
		// PR context: commit with [skip ci], push to feature branch.
		commitMsg := buildPRCommitMessage(opts)
		if err := gitCommitMulti(commitMsg, opts.RepoPath); err != nil {
			return err
		}
		log.Success("Changes committed successfully")
		fmt.Println()
		log.Info("Pushing commit to feature branch...")
		if err := gitPushBranch(opts.VersioningBranch, opts.RepoPath); err != nil {
			return err
		}
		log.Section("PR CHANGELOG GENERATION COMPLETE")
	} else {
		// Branch context: commit only, write flag.
		commitMsg := buildBranchCommitMessage(opts)
		if err := gitCommitMulti(commitMsg, opts.RepoPath); err != nil {
			return err
		}
		log.Success("Changes committed successfully")
		fmt.Println()
		// Write flag file
		if err := os.WriteFile(opts.FlagPath, []byte(""), 0o644); err != nil {
			return fmt.Errorf("changelog.update write flag %s: %w", opts.FlagPath, err)
		}
		log.Info("CHANGELOG committed — push deferred to branch-pipeline.sh (atomic with tag)")
		log.Section("BRANCH CHANGELOG GENERATION COMPLETE")
	}

	log.Info(fmt.Sprintf("Next Version: %s", opts.NextVersion))
	log.Info(fmt.Sprintf("Bump Type:    %s", opts.BumpType))
	fmt.Println()
	log.Info(fmt.Sprintf("%s has been updated", opts.ChangelogFile))
	if len(versionFiles) > 0 {
		log.Info("Version files have been updated")
	}
	if len(perFolderFiles) > 0 {
		log.Info("Per-folder CHANGELOGs have been updated")
	}

	return nil
}

// buildPRCommitMessage matches bash git commit -m lines for PR context.
func buildPRCommitMessage(opts UpdateOptions) []string {
	return []string{
		fmt.Sprintf("chore(release): update CHANGELOG for version %s (%s bump) [skip ci]", opts.NextVersion, opts.BumpType),
		"",
		fmt.Sprintf("This CHANGELOG will be included in the merge to %s.", opts.VersioningTargetBranch),
		"After merge, the version tag will be created automatically.",
		"",
		"Generated by CI Pipeline",
		fmt.Sprintf("Branch: %s", opts.VersioningBranch),
		fmt.Sprintf("PR: #%s", opts.PRID),
	}
}

// buildBranchCommitMessage matches bash git commit -m lines for branch context.
func buildBranchCommitMessage(opts UpdateOptions) []string {
	return []string{
		fmt.Sprintf("chore(release): update CHANGELOG for version %s (%s bump) [skip ci]", opts.NextVersion, opts.BumpType),
		"",
		"Generated by CI Pipeline",
		fmt.Sprintf("Branch: %s", opts.VersioningBranch),
	}
}

// changelogHasChanges replicates the bash changelog_has_changes() function.
func changelogHasChanges(changelogFile, repoPath string) bool {
	// If the file doesn't exist at all, there are no changes.
	if _, err := os.Stat(changelogFile); os.IsNotExist(err) {
		return false
	}
	// Check if file is modified (tracked and dirty)
	cmd := exec.Command("git", "diff", "--quiet", changelogFile)
	cmd.Dir = repoPath
	if cmd.Run() != nil {
		return true // exit non-zero = modified
	}
	// Check if file is new (exists but untracked)
	check := exec.Command("git", "ls-files", "--error-unmatch", changelogFile)
	check.Dir = repoPath
	if check.Run() != nil {
		return true // not tracked = new file
	}
	return false
}

func readVersionFiles(path string) []string {
	lines, _ := ReadLines(path)
	return lines
}

func readPerFolderChangelogs(path string) []string {
	if path == "" {
		return nil
	}
	lines, _ := ReadLines(path)
	// dedup
	seen := map[string]bool{}
	var out []string
	for _, l := range lines {
		if !seen[l] {
			seen[l] = true
			out = append(out, l)
		}
	}
	return out
}

func gitAdd(file, repoPath string) error {
	cmd := exec.Command("git", "add", file)
	cmd.Dir = repoPath
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("changelog.update git add %s: %w\n%s", file, err, string(out))
	}
	return nil
}

// gitCommitMulti runs git commit with multiple -m flags (one per element).
// This matches bash `git commit -m "msg1" -m "" -m "msg3"`.
func gitCommitMulti(lines []string, repoPath string) error {
	args := []string{"commit"}
	for _, l := range lines {
		args = append(args, "-m", l)
	}
	cmd := exec.Command("git", args...)
	cmd.Dir = repoPath
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("changelog.update git commit: %w\n%s", err, string(out))
	}
	return nil
}

func gitPushBranch(branch, repoPath string) error {
	cmd := exec.Command("git", "push", "origin", branch)
	cmd.Dir = repoPath
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("changelog.update git push %s: %w\n%s", branch, err, string(out))
	}
	return nil
}

// readState reads a single-line state file, trimming whitespace.
// Returns "" when the file doesn't exist.
func readState(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}
